function dfdx = ddx_central(f,dx)
    % This function computes the 1st derivative of f using a second-order
    % central difference scheme
    % Inputs: f (2D grid generated by ndgrid) dx (grid spacing)
    % Output: ddx (2D grid of 1st derivatives)
    % Credit: Ryan Dunn
    dfdx = zeros(size(f));
    for j = 1:size(f,2)
        i = 1;
        dfdx(i,j) = (-3*f(i,j) + 4*f(i+1,j) - f(i+2,j)) / (2*dx);
        for i = 2:size(f,1)-1
            dfdx(i,j) = (f(i+1,j) - f(i-1,j)) / (2*dx);
        end
        i = size(f,1);
        dfdx(i,j) = (3*f(i,j) - 4*f(i-1,j) + f(i-2,j)) / (2*dx);
    end
end