function dfdx = ddx_bwd(f,dx)
    % This function computes the 1st derivative of f using a first-order
    % backward difference scheme
    % Inputs: f (2D grid generated by ndgrid) dx (grid spacing)
    % Output: ddx (2D grid of 1st derivatives)
    % Credit: Ryan Dunn
    dfdx = zeros(size(f));
    for j = 1:size(f,2)
        i = 1;
        dfdx(i,j) = (f(i+1,j) - f(i,j))/dx;
        for i = 2:size(f,1)
            dfdx(i,j) = (f(i,j) - f(i-1,j))/dx;
        end
    end
end